DROP TABLE PL_ETL2;

--CREATE TABLE AND IMPORT DATE FROM ETL2.csv INTO THE TABLE
CREATE TABLE PL_ETL2(
  M_DATE	DATE,
  PLAYER_ID	INTEGER,
  PLAYER_SURNAME	VARCHAR2(20 ),
  PLAYER_FIRSTNAME	VARCHAR2(20),
  TEAM	VARCHAR2(50),
  TEAM_ID	INTEGER,
  OPPOSITION	VARCHAR2(50),
  OPPOSITION_ID	INTEGER,
  MINS_PLAYED	INTEGER,
  GOALS	INTEGER,
  SHOTS_ON_TARGET	INTEGER,
  SHOTS_OFF_TARGET	INTEGER,
  PENALTY_GOALS	INTEGER,
  TOTAL_SUCCESSFUL_PASSES	INTEGER,
  TOTAL_UNSUCCESSFUL_PASSES	INTEGER

);
--PART D
--ADD DATA FROM ETL TABLE INTO STAGE TABLES THEN ADD THEM TO DIM TABLES
SELECT * FROM PL_PLAYER_STAGE;
INSERT INTO PL_PLAYER_STAGE (PLAYER_ID,PLAYER_FIRSTNAME,PLAYER_SURNAME,TEAM_ID)
SELECT DISTINCT PLAYER_ID, PLAYER_FIRSTNAME, PLAYER_SURNAME, TEAM_ID FROM PL_ETL2 et WHERE
NOT EXISTS ( SELECT * FROM PL_PLAYER_STAGE ps WHERE ps.PLAYER_ID=et.PLAYER_ID);


INSERT INTO PL_DIM_PLAYER(PLAYER_FIRSTNAME,PLAYER_SURNAME)
SELECT DISTINCT PLAYER_FIRSTNAME, PLAYER_SURNAME FROM PL_PLAYER_STAGE ps WHERE
NOT EXISTS(SELECT * FROM PL_DIM_PLAYER dp where dp.player_sk=ps.player_sk);

INSERT INTO PL_TIME_STAGE (M_DATE,M_YEAR,M_MONTH,M_DAY)
SELECT DISTINCT M_DATE,cast(to_char(m_date,'YYYY') as integer), cast(to_char(m_date,'MM') as integer), cast(to_char(m_date,'DD')as integer) FROM PL_ETL2 et WHERE
NOT EXISTS ( SELECT * FROM PL_TIME_STAGE ts WHERE ts.M_DATE=et.M_DATE);
--no rows were inserted into the time stage so no need to add new rows to dim table

insert into PL_FACT_STAGE (TEAM_AID,TEAM_BID,M_DATE,PLAYER_ID,MIN_PLAYED,GOALS,SHOT_ON,SHOT_OFF,PENALTY,PASS_COMPLETE,PASS_INCOMPLETE) 
SELECT DISTINCT TEAM_ID,OPPOSITION_ID,M_DATE,PLAYER_ID,MINS_PLAYED,GOALS,SHOTS_ON_TARGET,SHOTS_OFF_TARGET,PENALTY_GOALS,TOTAL_SUCCESSFUL_PASSES,TOTAL_UNSUCCESSFUL_PASSES
FROM PL_ETL2 et WHERE
NOT EXISTS ( SELECT * FROM PL_FACT_STAGE fs WHERE fs.M_DATE=et.M_DATE AND fs.PLAYER_ID=et.PLAYER_ID);


insert into PL_DIM_FACT 
SELECT DISTINCT time_SK,player_sk,team_sk,opponent_sk,stadium_sk,min_played,goals,shot_on,shot_off,penalty,pass_complete,pass_incomplete 
from PL_FACT_STAGE ft WHERE
NOT EXISTS (SELECT * FROM PL_DIM_FACT WHERE ft.time_SK= PL_DIM_FACT.TIME_SK AND ft.PLAYER_SK=PL_DIM_FACT.PLAYER_SK);

